BEGIN TRANSACTION;
INSERT INTO `dxcc_area` VALUES (NULL, 'DL','Bindow',14,28,'Eu','JO62UG');
INSERT INTO `dxcc_area` VALUES (NULL, 'DL','Dresden',14,28,'Eu','JO61UB');
INSERT INTO `dxcc_area` VALUES (NULL, 'DL','Frankfurt',14,28,'Eu','JO40GB');
INSERT INTO `dxcc_area` VALUES (NULL, 'DL','HH Langenhorn',14,28,'Eu','JO53AP');
INSERT INTO `dxcc_area` VALUES (NULL, 'DL','Munic',14,28,'Eu','JN58TD');
INSERT INTO `dxcc_area` VALUES (NULL, 'JA','JA2',25,45,'As','PM85MM');
INSERT INTO `dxcc_area` VALUES (NULL, 'JA','JA6',25,45,'As','PM52MM');
INSERT INTO `dxcc_area` VALUES (NULL, 'JA','JA8',25,45,'As','QN13MM');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA','UA1',16,19,'Eu','KP71LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA','UA3',16,29,'Eu','KO85LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA','UA4',16,30,'Eu','LO66LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA8',8,33,'As','OO62LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA9 ITU:20',17,20,'As','LP51LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA9 ITU:21',17,21,'As','MP80LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA9 ITU:30',17,30,'As','LO84LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:32',18,32,'As','OO22LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:33',18,33,'As','OO62LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:34',19,34,'As','PN78LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:22',18,22,'As','OP04LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:24',19,24,'As','QP14LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:25',19,25,'As','RP01LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:26',19,26,'As','RP84LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA0 ITU:35',19,35,'As','QO93LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'UA9','UA9 ITU:31',18,31,'As','NO15LL');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE1 Novo Scotia',5,9,'NA','FN84FO');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE2 Quebec',5,4,'NA','FN35EL');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE3 Ontario',4,4,'NA','EO70BK');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE4 Manitoba',4,4,'NA','EO13JL');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE5 Saskatchewan',4,3,'NA','DO61RX');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE6 Alberta',4,2,'NA','DO33HJ');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE7 British Columbia',3,2,'NA','CO81HU');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE8 N.W.T',4,3,'NA','CP74KG');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VE9 New Brunswick',5,9,'NA','FN65QV');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VO1 Newfoundland',2,9,'NA','GN28RX');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VO2 Labrador',5,9,'NA','FO93PO');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VY0 Nunavut',2,4,'NA','EP14FL');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VY1 Yukon',1,2,'NA','CP23SP');
INSERT INTO `dxcc_area` VALUES (NULL, 'VE','VY2 Prince Edward Is.',5,9,'NA','FN89NK');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W0',4,7,'NA','EM08AA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W1',5,8,'NA','FN65AA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W2',5,8,'NA','FN20PS');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W3',5,8,'NA','FM19MA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W4',5,8,'NA','EM85AA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W5',4,7,'NA','EM12PO');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W6',3,6,'NA','CM98HF');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W7',3,6,'NA','DM39MA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W8',4,8,'NA','EN82MA');
INSERT INTO `dxcc_area` VALUES (NULL, 'W','W9',4,8,'NA','EN62MA');
COMMIT;
