ns/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.13.0"
      - name: npm install
        uses: jaid/action-npm-install@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Jest
        uses: jaid/action-jest@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: jaid/action-publish@master
        with:
          githubToken: ${{ secrets.packagesToken }}
          npmPrepareScript: build:prod
          publishDirectory: dist/package/production
          npmToken: ${{ secrets.npmToken }}